question_data = [{"category": "Entertainment: Video Games",
                              "type": "multiple",
                              "difficulty": "hard",
                              "question": "How many people can you recruit in the game Suikoden in a single playthrough?",
                              "correct_answer": "107",
                              "incorrect_answers": ["108",
                                                    "93",
                                                    "96"]},
                 {"category": "Entertainment: Music",
                              "type": "multiple",
                              "difficulty": "medium",
                              "question": "Who had a US and UK number 1 hit in 1962 with the instrumental, &#039;Telstar&#039;?",
                              "correct_answer": "The Tornados",
                              "incorrect_answers": ["The Ventures",
                                                    "The Spotnicks",
                                                    "The Tremeloes"]},
                 {"category": "Sports",
                              "type": "multiple",
                              "difficulty": "medium",
                              "question": "A stimpmeter measures the speed of a ball over what surface?",
                              "correct_answer": "Golf Putting Green",
                              "incorrect_answers": [" Football Pitch",
                                                    "Cricket Outfield",
                                                    "Pinball Table"]},
                 {"category": "Science & Nature",
                              "type": "multiple",
                              "difficulty": "hard",
                              "question": "What is the molecular formula of Glucose?",
                              "correct_answer": "C6H12O6",
                              "incorrect_answers": ["C2H4O2",
                                                    "K+",
                                                    "CH4"]},
                 {"category": "Entertainment: Film",
                              "type": "multiple",
                              "difficulty": "medium",
                              "question": "This movie contains the quote, &quot;I love the smell of napalm in the morning!&quot;",
                              "correct_answer": "Apocalypse Now",
                              "incorrect_answers": ["Platoon",
                                                    "The Deer Hunter",
                                                    "Full Metal Jacket"]},
                 {"category": "Science: Computers",
                              "type": "multiple",
                              "difficulty": "medium",
                              "question": "Which of the following languages is used as a scripting language in the Unity 3D game engine?",
                              "correct_answer": "C#",
                              "incorrect_answers": ["Java",
                                                    "C++",
                                                    "Objective-C"]},
                 {"category": "Entertainment: Japanese Anime & Manga",
                              "type": "multiple",
                              "difficulty": "medium",
                              "question": "In &quot;Shakugan no Shana&quot; what was the Shana usually referred as?",
                              "correct_answer": "Flame-Haired Burning-Eyed Hunter",
                              "incorrect_answers": ["Flame Haze",
                                                    "Flame-Haired Burning-Eyed Haze",
                                                    "Shana"]},
                 {"category": "Entertainment: Video Games",
                              "type": "boolean",
                              "difficulty": "medium",
                              "question": "In &quot;Overwatch,&quot; an allied McCree will say &quot;Step right up&quot; upon using his ultimate ability Deadeye.",
                              "correct_answer": "True",
                              "incorrect_answers": ["False"]},
                 {"category": "Science & Nature",
                              "type": "multiple",
                              "difficulty": "hard",
                              "question": "What genetic disease is caused by having an extra Y chromosome (XYY)?",
                              "correct_answer": "Jacob&#039;s Syndrome",
                              "incorrect_answers": ["Klinefelter&#039;s Syndrome",
                                                    "Turner&#039;s Syndrome",
                                                    "Down Syndrome"]},
                 {"category": "Entertainment: Books",
                              "type": "multiple",
                              "difficulty": "hard",
                              "question": "In the Magic: The Gathering universe,  the Antiquities, Ice Age, and Alliances expansions take place on which continent?",
                              "correct_answer": "Terisiare",
                              "incorrect_answers": ["Aerona",
                                                    "Shiv",
                                                    "Jamuraa"]}]
